package com.sir.opsc_coincontrol

data class CategoryClass(

    var cat_ID: Int = 0, // ID should be 0 or omitted since it's auto-generated by the server
    var categoryName: String,
    var userID: Int = 0, // This can be 0 or omitted, as the backend will assign it
    var budget: Double,
    var amountSpent: Double,
    var average: Double
)